version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: blog-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: blogdb
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: blog-backend
    restart: always
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb://admin:adminpassword@mongo:27017/blogdb?authSource=admin
      PORT: 5000
      JWT_SECRET: unSecretTresFort
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    command: node server.js

volumes:
  mongo-data:
